language: node_js
node_js:
- '10'
install:
- yarn
script:
- yarn check
deploy:
  provider: npm
  email:
    secure: Blwpq3RrG3ayQLV5gt1eqPTx2C+OI1HEKQwJrkgVVdd0gfBrJybP6KJ0EVJcLTvO1WyTmFzmBVMu/G4IgqQU/Uldj6bqmgnT0EDN3qZL3H1Eegfj4aoBT1Y5p9Ye7h3K12dp7RwKkCoqKGfdoMcnwt4K1Sa/s+DTuqrYk9Xd+xqj5Vf3WbYg8nIYcP4FVfqqI5g03+GXRpMCRmaiW7RLWksRO83GFMPRXPTxPAqaX5Czu1gJoK2/T0gCZ7fhOcc8m8m26rzpzv2Y0jLt8bv7ndbDn28bIt4sW73/lTcy99p749Z4oidn9IH84jhHaBAZ3GUBAJKHMnlgzdT+ky4FUaNA50Wngt+2fzyyLaKgt2fYOm4QcQAH1fFguCxYNSeBiIu7uwON9+K5nS/7GxmHFe5Cd13kDiZMPtL2Lv/3GW5kTO4Dz1teuZcMiOTBsSwICye4am7E6uek9XsVbzO32c8QXUAmwDGJRWhSlX0fzuXqPnF0LAaqI9NK1FvEbcAwZlEnw6hRZzfed9hfblHlavgNNA17wkO7f3yFdEpEBEC+4SAHnalC+9ha7lHVTkuNNjJ1XdOGshbx6bEAulxMMwhgmzFMNGlGfECmbec3PrNcBqOmnlIa5SNUOxmq77+exiwz216QKRrOtD9/VfFGA9Cnr0DSf29XnQKNKW5Pko0=
  script: yarn build
  api_key:
    secure: OSPa4cPZtrwb6NxgxhUfW7GQeCb8atg+Mdedg79uUmIt61yEcCYy38jeViYBkwORB7S6Vb2PZc5MP3Jj9JPy9HBNH/O20e5hCqSG+pfSmZsUPOTWWbSuG2XmvLtUQP01Bq5B9SXGB1cnCmYoWj4r4JQTBekFFFEC9TTMFVVJ7cy3GdXgjCdEjS1S1hnrDRkOJGQsgJmOjjzAmLtwQq9VieuxU4DGuPMtPcVCDJXsZoSJSJOl7MjAHMr/Rxj/hjwkK9YkgoBllrBJctTGnYge4gWgYJduKdnBUpLfR0RMgjPfNbzly9sO7/dekujn0cnaFjYnIQojYvqj10WoZJ5u+AO7IF9OAAfBxAKBxJJ7ZXwz1HTbnzoxpV0z40Omd1bKW5CjaC/r/XditoKo89F8ryzgv3X/skUVbMcHXGsTuuzeq+nxN6XrjZICfd0tJxAtAGQZoIkzJdGhQ34PxJyZtq7TEanne0E6HmJOaZUgneZRlDxCNNi31kuQMZnd7CLy6VKcj6iHX6d7uisV6P05iWjvJnVeocgK+us2fwq4QSyXpJo1p2s1/RAG11vz1SwLW7e7Pw4pskMZQPxVRtiSs4evglBiR1+eW9IkvMIemHw6KyfhXIm7G61HSTMqkb+GWPX2kn0nXokTFBFBoY3J6Aws3bzneCBkyNJ3LfEfhlY=
  skip_cleanup: true
  on:
    tags: true
    repo: Evalon/yarnd
